# Generated by Django 3.2.9 on 2021-12-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portfolio.website')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('commenced', models.DateField()),
                ('completed', models.DateField()),
                ('description', models.TextField(max_length=1000)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolio.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('issued', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolio.documenttype')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portfolio.experience')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolio.institution')),
            ],
        ),
    ]
