# Generated by Django 3.2.9 on 2021-12-03 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='experience',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='portfolio.experience'),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
