# Generated by Django 3.2.9 on 2021-12-03 22:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211203_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_type',
            new_name='document_type_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='experience',
            new_name='experience_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='issued',
            new_name='issued_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='issuer',
            new_name='issuer_id',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='institution',
            new_name='institution_id',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='website',
            new_name='website_id',
        ),
        migrations.AddField(
            model_name='experience',
            name='type',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
