# Generated by Django 3.2.9 on 2021-12-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211204_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type_id',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='portfolio.documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issued_id',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='commenced',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('Education', 'Learning Experience'), ('Employement', 'Employment Experience'), ('Project', 'Project Experience')], default='', max_length=100),
        ),
    ]
