# Generated by Django 3.2.9 on 2021-12-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
