# Generated by Django 3.2.9 on 2021-12-04 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_documenttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
