# Generated by Django 3.2.9 on 2021-12-04 00:21

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_documenttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.IntegerField(default=django.db.models.fields.AutoField, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
