# Generated by Django 3.2.9 on 2021-12-04 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_institution_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='issued_id',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='commenced',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='completed',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(to='portfolio.Tag'),
        ),
    ]
