# Generated by Django 3.2.9 on 2021-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20211204_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='interest',
            name='image',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(default='Default.png', upload_to=''),
        ),
    ]
