# Generated by Django 3.2.9 on 2021-12-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.Tag'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
