# Generated by Django 3.2.9 on 2021-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20211208_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='completed',
            field=models.DateTimeField(),
        ),
    ]
