# Generated by Django 3.2.9 on 2021-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_experience_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='completed',
            field=models.DateTimeField(default='00:00'),
        ),
    ]
