# Generated by Django 3.2.9 on 2021-12-31 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_document_issued_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='commenced',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, 1)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='completed',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, 1)),
        ),
    ]
