# Generated by Django 3.2.9 on 2021-12-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20211231_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='issued_id',
            field=models.DateTimeField(default='2020/01/01 00:00'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='commenced',
            field=models.DateTimeField(default='2020/01/01 00:00'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='completed',
            field=models.DateTimeField(default='2020/01/01 00:00'),
        ),
    ]
