# Generated by Django 3.2.9 on 2022-01-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20220107_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('video', models.FileField(upload_to='video/%y')),
                ('document_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='portfolio.documenttype')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='video',
            field=models.ManyToManyField(blank=True, to='portfolio.Video'),
        ),
    ]
