# Generated by Django 3.2.9 on 2022-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_auto_20220108_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='websites',
            field=models.ManyToManyField(blank=True, to='portfolio.Website'),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
