# Generated by Django 4.0.1 on 2022-01-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
