# Generated by Django 4.0.1 on 2022-01-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='video',
            new_name='videos',
        ),
    ]
