# Generated by Django 4.0.1 on 2022-01-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_alter_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='clip',
        ),
    ]
