# Generated by Django 4.0.1 on 2022-01-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='portfolio.Document'),
        ),
    ]
