# Generated by Django 4.0.1 on 2022-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0039_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=2100),
        ),
    ]
