# Generated by Django 4.0.1 on 2022-01-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_remove_video_mp4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='webm',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='documents',
            field=models.ManyToManyField(to='portfolio.Document'),
        ),
    ]
