# Generated by Django 4.0.1 on 2022-01-15 21:30

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_remove_video_webm_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
