# Generated by Django 4.0.1 on 2022-01-15 21:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
