# Generated by Django 4.0.1 on 2022-01-15 21:42

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_remove_video_url_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
